select * from customer limit 20

SELECT column_name
FROM information_schema.columns
WHERE table_name = 'customer';

--1. what is the total revenue generated by male vs female
SELECT gender, SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY gender;

--2. which customer used a discunt but still spent more than the avg purchase amount?
select customer_id, purchase_amount
from customer 
where discount_applied = 'Yes' and purchase_amount > (select avg(purchase_amount) from customer)

--3. which are the top 5 products with the highest avg review rating?
select item_purchased, round(avg(review_rating ::numeric),2) as "Average Product Rating"
from customer
group by item_purchased 
order by avg(review_rating) desc
limit 5

--4.compare the average purchase amounts between standard and express shipping 


